services:
  postgres:
    image: postgres:16
    container_name: postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d subscriptions"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: subscription-api
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      CONFIG_PATH: /app/config/local.yaml
    volumes:
      - ./config:/app/config
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: {}
