services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d subscriptions -h 127.0.0.1" ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 30s


  app:
    build: .
    container_name: subscription-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: ./config/local.yaml
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: {}
