env: "local"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s
storage:
  address: "postgres:5432"
  user: "postgres"
  password: "postgres"
  database: "subscriptions"
  minConns: 2
  maxConns: 10
  maxConnLifetime: 3600s
  HealthCheckPeriod: 30s
  MaxConnIdleTime: 60s
  StatementTimeout: 5000
  IdleInTransactionSessionTimeout: 5000
